<?php
require_once 'vendor/autoload.php';
use ImalH\PDFLib\PDF;
use ImalH\PDFLib\Drivers\TesseractDriver;

echo "Starting OCR test...\n";

// We need a dummy PDF with text (or image) but since Tesseract converts PDF to image via GS, any PDF works.
// Let's use the one generated by sips earlier or sample.
// We created 'test_sips.pdf' in step 129
$source = __DIR__ . '/test_sips.pdf';
if (!file_exists($source)) {
    // try invalid source to see error or copy from banner
    // sips logic again
    exec("sips -s format pdf banner.png --out test_ocr.pdf");
    $source = __DIR__ . '/test_ocr.pdf';
}

$outputFile = __DIR__ . '/api/output/test_job_ocr.txt'; // Tesseract outputs text
// Driver handles ext? 
// Driver adds .txt itself.

echo "Source: $source\n";

try {
    $pdf = new PDF(new TesseractDriver());
    $pdf->from($source);
    // ocr() destination logic in driver:
    // $outputBase = preg_replace('/\.txt$/i', '', $destination);
    // ... command ... output_base
    // Tesseract adds .txt

    // We pass full path hoping driver renames or we handle it.
    // Driver logic:
    // $actualFile = $outputBase . '.txt';
    // if ($actualFile !== $destination) rename($actualFile, $destination);

    $result = $pdf->ocr($outputFile);

    if ($result && file_exists($outputFile)) {
        echo "SUCCESS: OCR created $outputFile\n";
        echo "Content: " . substr(file_get_contents($outputFile), 0, 50) . "...\n";
    } else {
        echo "FAILED: result false or file missing.\n";
    }

} catch (Exception $e) {
    echo "EXCEPTION: " . $e->getMessage() . "\n";
}
